-- Generated by scripts/export-sql.mjs — do not edit by hand.
-- Import in hPanel → phpMyAdmin with your database selected.
-- Safe to re-import: every statement upserts.

SET NAMES utf8mb4;

-- ----------------------------------------------------------------------
-- Services
-- ----------------------------------------------------------------------

INSERT INTO services (id, title, nav_label, description, outcome, intro, related_extras, active, sort_order)
VALUES ('logo-design', 'Logo Design', 'Logo Design', 'Marks that stick. Every logo ships in SVG, PDF and PNG with color and mono versions.', 'A mark that holds up at 16 pixels and on a shopfront.', 'Most logos fail somewhere: they blur at favicon size, fall apart in one colour, or look like three other businesses in the same category. The work starts from what your brand actually has to survive, a phone screen, an embroidered shirt, a printed invoice, and designs backwards from that.', '[]', 1, 0)
ON DUPLICATE KEY UPDATE title = VALUES(title), nav_label = VALUES(nav_label), description = VALUES(description), outcome = VALUES(outcome), intro = VALUES(intro), related_extras = VALUES(related_extras), active = VALUES(active), sort_order = VALUES(sort_order);

INSERT INTO services (id, title, nav_label, description, outcome, intro, related_extras, active, sort_order)
VALUES ('brand-guidelines', 'Brand Guidelines', 'Brand Guidelines', 'The rulebook for your brand. Clear rules for logo, colour and type, so every future design stays on point.', 'Everything anyone needs to use your brand without asking you first.', 'A logo is one asset. A brand is a system, and the moment a second person touches it (a printer, a developer, a freelancer, a future employee) the system either holds or drifts. Guidelines are what keep the fifth thing you make look related to the first.', '[]', 1, 1)
ON DUPLICATE KEY UPDATE title = VALUES(title), nav_label = VALUES(nav_label), description = VALUES(description), outcome = VALUES(outcome), intro = VALUES(intro), related_extras = VALUES(related_extras), active = VALUES(active), sort_order = VALUES(sort_order);

INSERT INTO services (id, title, nav_label, description, outcome, intro, related_extras, active, sort_order)
VALUES ('animation', 'Logo Animation', 'Logo Animation', 'Logo reveals and motion identities in MP4 and GIF, ready for web, decks and social.', 'Your logo, resolving in motion.', 'A static mark says what you are. A mark that resolves in motion says you built something. Animation is the smallest upgrade with the largest perceived one: the first frame of a video, the loader on a site, the sting at the end of an ad.', '[]', 1, 2)
ON DUPLICATE KEY UPDATE title = VALUES(title), nav_label = VALUES(nav_label), description = VALUES(description), outcome = VALUES(outcome), intro = VALUES(intro), related_extras = VALUES(related_extras), active = VALUES(active), sort_order = VALUES(sort_order);

INSERT INTO services (id, title, nav_label, description, outcome, intro, related_extras, active, sort_order)
VALUES ('social-media', 'Social Media Kit', 'Social Media Kit', 'Feed templates, stories and campaign tiles sized for every platform and built to stop the scroll.', 'A feed that looks designed rather than assembled.', 'Social is where most brands quietly come apart. A different font every week, a logo squashed into a circle, screenshots posted as artwork. The fix is not more posts, it is a small set of templates that are faster to use than to ignore.', '[\"Social Media Kit\"]', 1, 3)
ON DUPLICATE KEY UPDATE title = VALUES(title), nav_label = VALUES(nav_label), description = VALUES(description), outcome = VALUES(outcome), intro = VALUES(intro), related_extras = VALUES(related_extras), active = VALUES(active), sort_order = VALUES(sort_order);

INSERT INTO services (id, title, nav_label, description, outcome, intro, related_extras, active, sort_order)
VALUES ('stationery', 'Stationery Design', 'Stationery Design', 'Business cards, letterheads and envelopes, print ready for any shop.', 'Print files you can send to any printer without a phone call.', 'Stationery is where a brand stops being a screen and becomes an object someone holds. It is also where amateur work shows fastest: wrong bleed, low-resolution logos, type that dies at the trim. Files go out print-ready, with bleed and crop marks, so the print shop has nothing to query.', '[\"Stationery Design Kit\",\"Business Card\"]', 1, 4)
ON DUPLICATE KEY UPDATE title = VALUES(title), nav_label = VALUES(nav_label), description = VALUES(description), outcome = VALUES(outcome), intro = VALUES(intro), related_extras = VALUES(related_extras), active = VALUES(active), sort_order = VALUES(sort_order);

-- ----------------------------------------------------------------------
-- Projects (8)
-- ----------------------------------------------------------------------

-- GUILDVEIL Brand Guidelines
INSERT INTO projects (slug, title, category, logo_type, guideline_type, industry, website, instagram, facebook, linkedin, other_links, extras, extras_custom, sort_order, summary, intent, context, challenge, direction, delivered, outcome, testimonial, pdf, cover, cover_alt)
VALUES ('guildveil-brand-guidelines', 'GUILDVEIL Brand Guidelines', 'brand-guidelines', 'Lettermark', 'Full Brand Guidelines', 'Tattoo', NULL, NULL, NULL, NULL, '[]', '[\"Stationery Design Kit\"]', '[]', 2, 'A distinctive brand identity designed for GUILDVEIL, a dark fantasy tattoo studio inspired by forgotten folklore, aged libraries, and quiet mystery. The visual system blends gothic elegance with modern craftsmanship, creating an immersive brand experience that reflects fine line, blackwork, and illustrative tattoo artistry.', 'Gothic elegance drawn with modern craft, for a dark-fantasy tattoo studio.', NULL, NULL, NULL, '[]', NULL, NULL, 'GUILDVEIL Brand Guidelines.pdf', './cover.png', 'GUILDVEIL Brand Guidelines presentation cover')
ON DUPLICATE KEY UPDATE title = VALUES(title), category = VALUES(category), logo_type = VALUES(logo_type), guideline_type = VALUES(guideline_type), industry = VALUES(industry), website = VALUES(website), instagram = VALUES(instagram), facebook = VALUES(facebook), linkedin = VALUES(linkedin), other_links = VALUES(other_links), extras = VALUES(extras), extras_custom = VALUES(extras_custom), sort_order = VALUES(sort_order), summary = VALUES(summary), intent = VALUES(intent), context = VALUES(context), challenge = VALUES(challenge), direction = VALUES(direction), delivered = VALUES(delivered), outcome = VALUES(outcome), testimonial = VALUES(testimonial), pdf = VALUES(pdf), cover = VALUES(cover), cover_alt = VALUES(cover_alt);
DELETE FROM project_images WHERE project_slug = 'guildveil-brand-guidelines';
INSERT INTO project_images (project_slug, sort_order, src, alt) VALUES
  ('guildveil-brand-guidelines', 0, './page-01.png', 'GUILDVEIL Brand Guidelines presentation, page 1 of 36'),
  ('guildveil-brand-guidelines', 1, './page-02.png', 'GUILDVEIL Brand Guidelines presentation, page 2 of 36'),
  ('guildveil-brand-guidelines', 2, './page-03.png', 'GUILDVEIL Brand Guidelines presentation, page 3 of 36'),
  ('guildveil-brand-guidelines', 3, './page-04.png', 'GUILDVEIL Brand Guidelines presentation, page 4 of 36'),
  ('guildveil-brand-guidelines', 4, './page-05.png', 'GUILDVEIL Brand Guidelines presentation, page 5 of 36'),
  ('guildveil-brand-guidelines', 5, './page-06.png', 'GUILDVEIL Brand Guidelines presentation, page 6 of 36'),
  ('guildveil-brand-guidelines', 6, './page-07.png', 'GUILDVEIL Brand Guidelines presentation, page 7 of 36'),
  ('guildveil-brand-guidelines', 7, './page-08.png', 'GUILDVEIL Brand Guidelines presentation, page 8 of 36'),
  ('guildveil-brand-guidelines', 8, './page-09.png', 'GUILDVEIL Brand Guidelines presentation, page 9 of 36'),
  ('guildveil-brand-guidelines', 9, './page-10.png', 'GUILDVEIL Brand Guidelines presentation, page 10 of 36'),
  ('guildveil-brand-guidelines', 10, './page-11.png', 'GUILDVEIL Brand Guidelines presentation, page 11 of 36'),
  ('guildveil-brand-guidelines', 11, './page-12.png', 'GUILDVEIL Brand Guidelines presentation, page 12 of 36'),
  ('guildveil-brand-guidelines', 12, './page-13.png', 'GUILDVEIL Brand Guidelines presentation, page 13 of 36'),
  ('guildveil-brand-guidelines', 13, './page-14.png', 'GUILDVEIL Brand Guidelines presentation, page 14 of 36'),
  ('guildveil-brand-guidelines', 14, './page-15.png', 'GUILDVEIL Brand Guidelines presentation, page 15 of 36'),
  ('guildveil-brand-guidelines', 15, './page-16.png', 'GUILDVEIL Brand Guidelines presentation, page 16 of 36'),
  ('guildveil-brand-guidelines', 16, './page-17.png', 'GUILDVEIL Brand Guidelines presentation, page 17 of 36'),
  ('guildveil-brand-guidelines', 17, './page-18.png', 'GUILDVEIL Brand Guidelines presentation, page 18 of 36'),
  ('guildveil-brand-guidelines', 18, './page-19.png', 'GUILDVEIL Brand Guidelines presentation, page 19 of 36'),
  ('guildveil-brand-guidelines', 19, './page-20.png', 'GUILDVEIL Brand Guidelines presentation, page 20 of 36'),
  ('guildveil-brand-guidelines', 20, './page-21.png', 'GUILDVEIL Brand Guidelines presentation, page 21 of 36'),
  ('guildveil-brand-guidelines', 21, './page-22.png', 'GUILDVEIL Brand Guidelines presentation, page 22 of 36'),
  ('guildveil-brand-guidelines', 22, './page-23.png', 'GUILDVEIL Brand Guidelines presentation, page 23 of 36'),
  ('guildveil-brand-guidelines', 23, './page-24.png', 'GUILDVEIL Brand Guidelines presentation, page 24 of 36'),
  ('guildveil-brand-guidelines', 24, './page-25.png', 'GUILDVEIL Brand Guidelines presentation, page 25 of 36'),
  ('guildveil-brand-guidelines', 25, './page-26.png', 'GUILDVEIL Brand Guidelines presentation, page 26 of 36'),
  ('guildveil-brand-guidelines', 26, './page-27.png', 'GUILDVEIL Brand Guidelines presentation, page 27 of 36'),
  ('guildveil-brand-guidelines', 27, './page-28.png', 'GUILDVEIL Brand Guidelines presentation, page 28 of 36'),
  ('guildveil-brand-guidelines', 28, './page-29.png', 'GUILDVEIL Brand Guidelines presentation, page 29 of 36'),
  ('guildveil-brand-guidelines', 29, './page-30.png', 'GUILDVEIL Brand Guidelines presentation, page 30 of 36'),
  ('guildveil-brand-guidelines', 30, './page-31.png', 'GUILDVEIL Brand Guidelines presentation, page 31 of 36'),
  ('guildveil-brand-guidelines', 31, './page-32.png', 'GUILDVEIL Brand Guidelines presentation, page 32 of 36'),
  ('guildveil-brand-guidelines', 32, './page-33.png', 'GUILDVEIL Brand Guidelines presentation, page 33 of 36'),
  ('guildveil-brand-guidelines', 33, './page-34.png', 'GUILDVEIL Brand Guidelines presentation, page 34 of 36'),
  ('guildveil-brand-guidelines', 34, './page-35.png', 'GUILDVEIL Brand Guidelines presentation, page 35 of 36'),
  ('guildveil-brand-guidelines', 35, './page-36.png', 'GUILDVEIL Brand Guidelines presentation, page 36 of 36');

-- Materia Bioworks Brand Guidelines
INSERT INTO projects (slug, title, category, logo_type, guideline_type, industry, website, instagram, facebook, linkedin, other_links, extras, extras_custom, sort_order, summary, intent, context, challenge, direction, delivered, outcome, testimonial, pdf, cover, cover_alt)
VALUES ('materia-bioworks-brand-guidelines', 'Materia Bioworks Brand Guidelines', 'brand-guidelines', 'Combination', 'Full Brand Guidelines', 'Sustainable Materials & Biotechnology', 'www.materiabioworks.com', NULL, NULL, NULL, '[]', '[\"Stationery Design Kit\",\"Mockups\"]', '[]', 3, 'A forward-thinking brand identity created for Materia Bioworks, a biotechnology company accelerating the commercialization of next-generation sustainable materials. The visual system balances scientific precision with modern innovation, establishing a trusted and scalable identity that reflects collaboration, advanced engineering, and a commitment to shaping a more sustainable future.', 'Scientific precision made investable for a sustainable-materials company.', NULL, NULL, NULL, '[]', NULL, NULL, 'Materia Bioworks Brand Guidelines.pdf', './cover.png', 'Materia Bioworks Brand Guidelines presentation cover')
ON DUPLICATE KEY UPDATE title = VALUES(title), category = VALUES(category), logo_type = VALUES(logo_type), guideline_type = VALUES(guideline_type), industry = VALUES(industry), website = VALUES(website), instagram = VALUES(instagram), facebook = VALUES(facebook), linkedin = VALUES(linkedin), other_links = VALUES(other_links), extras = VALUES(extras), extras_custom = VALUES(extras_custom), sort_order = VALUES(sort_order), summary = VALUES(summary), intent = VALUES(intent), context = VALUES(context), challenge = VALUES(challenge), direction = VALUES(direction), delivered = VALUES(delivered), outcome = VALUES(outcome), testimonial = VALUES(testimonial), pdf = VALUES(pdf), cover = VALUES(cover), cover_alt = VALUES(cover_alt);
DELETE FROM project_images WHERE project_slug = 'materia-bioworks-brand-guidelines';
INSERT INTO project_images (project_slug, sort_order, src, alt) VALUES
  ('materia-bioworks-brand-guidelines', 0, './page-01.png', 'Materia Bioworks Brand Guidelines presentation, page 1 of 45'),
  ('materia-bioworks-brand-guidelines', 1, './page-02.png', 'Materia Bioworks Brand Guidelines presentation, page 2 of 45'),
  ('materia-bioworks-brand-guidelines', 2, './page-03.png', 'Materia Bioworks Brand Guidelines presentation, page 3 of 45'),
  ('materia-bioworks-brand-guidelines', 3, './page-04.png', 'Materia Bioworks Brand Guidelines presentation, page 4 of 45'),
  ('materia-bioworks-brand-guidelines', 4, './page-05.png', 'Materia Bioworks Brand Guidelines presentation, page 5 of 45'),
  ('materia-bioworks-brand-guidelines', 5, './page-06.png', 'Materia Bioworks Brand Guidelines presentation, page 6 of 45'),
  ('materia-bioworks-brand-guidelines', 6, './page-07.png', 'Materia Bioworks Brand Guidelines presentation, page 7 of 45'),
  ('materia-bioworks-brand-guidelines', 7, './page-08.png', 'Materia Bioworks Brand Guidelines presentation, page 8 of 45'),
  ('materia-bioworks-brand-guidelines', 8, './page-09.png', 'Materia Bioworks Brand Guidelines presentation, page 9 of 45'),
  ('materia-bioworks-brand-guidelines', 9, './page-10.png', 'Materia Bioworks Brand Guidelines presentation, page 10 of 45'),
  ('materia-bioworks-brand-guidelines', 10, './page-11.png', 'Materia Bioworks Brand Guidelines presentation, page 11 of 45'),
  ('materia-bioworks-brand-guidelines', 11, './page-12.png', 'Materia Bioworks Brand Guidelines presentation, page 12 of 45'),
  ('materia-bioworks-brand-guidelines', 12, './page-13.png', 'Materia Bioworks Brand Guidelines presentation, page 13 of 45'),
  ('materia-bioworks-brand-guidelines', 13, './page-14.png', 'Materia Bioworks Brand Guidelines presentation, page 14 of 45'),
  ('materia-bioworks-brand-guidelines', 14, './page-15.png', 'Materia Bioworks Brand Guidelines presentation, page 15 of 45'),
  ('materia-bioworks-brand-guidelines', 15, './page-16.png', 'Materia Bioworks Brand Guidelines presentation, page 16 of 45'),
  ('materia-bioworks-brand-guidelines', 16, './page-17.png', 'Materia Bioworks Brand Guidelines presentation, page 17 of 45'),
  ('materia-bioworks-brand-guidelines', 17, './page-18.png', 'Materia Bioworks Brand Guidelines presentation, page 18 of 45'),
  ('materia-bioworks-brand-guidelines', 18, './page-19.png', 'Materia Bioworks Brand Guidelines presentation, page 19 of 45'),
  ('materia-bioworks-brand-guidelines', 19, './page-20.png', 'Materia Bioworks Brand Guidelines presentation, page 20 of 45'),
  ('materia-bioworks-brand-guidelines', 20, './page-21.png', 'Materia Bioworks Brand Guidelines presentation, page 21 of 45'),
  ('materia-bioworks-brand-guidelines', 21, './page-22.png', 'Materia Bioworks Brand Guidelines presentation, page 22 of 45'),
  ('materia-bioworks-brand-guidelines', 22, './page-23.png', 'Materia Bioworks Brand Guidelines presentation, page 23 of 45'),
  ('materia-bioworks-brand-guidelines', 23, './page-24.png', 'Materia Bioworks Brand Guidelines presentation, page 24 of 45'),
  ('materia-bioworks-brand-guidelines', 24, './page-25.png', 'Materia Bioworks Brand Guidelines presentation, page 25 of 45'),
  ('materia-bioworks-brand-guidelines', 25, './page-26.png', 'Materia Bioworks Brand Guidelines presentation, page 26 of 45'),
  ('materia-bioworks-brand-guidelines', 26, './page-27.png', 'Materia Bioworks Brand Guidelines presentation, page 27 of 45'),
  ('materia-bioworks-brand-guidelines', 27, './page-28.png', 'Materia Bioworks Brand Guidelines presentation, page 28 of 45'),
  ('materia-bioworks-brand-guidelines', 28, './page-29.png', 'Materia Bioworks Brand Guidelines presentation, page 29 of 45'),
  ('materia-bioworks-brand-guidelines', 29, './page-30.png', 'Materia Bioworks Brand Guidelines presentation, page 30 of 45'),
  ('materia-bioworks-brand-guidelines', 30, './page-31.png', 'Materia Bioworks Brand Guidelines presentation, page 31 of 45'),
  ('materia-bioworks-brand-guidelines', 31, './page-32.png', 'Materia Bioworks Brand Guidelines presentation, page 32 of 45'),
  ('materia-bioworks-brand-guidelines', 32, './page-33.png', 'Materia Bioworks Brand Guidelines presentation, page 33 of 45'),
  ('materia-bioworks-brand-guidelines', 33, './page-34.png', 'Materia Bioworks Brand Guidelines presentation, page 34 of 45'),
  ('materia-bioworks-brand-guidelines', 34, './page-35.png', 'Materia Bioworks Brand Guidelines presentation, page 35 of 45'),
  ('materia-bioworks-brand-guidelines', 35, './page-36.png', 'Materia Bioworks Brand Guidelines presentation, page 36 of 45'),
  ('materia-bioworks-brand-guidelines', 36, './page-37.png', 'Materia Bioworks Brand Guidelines presentation, page 37 of 45'),
  ('materia-bioworks-brand-guidelines', 37, './page-38.png', 'Materia Bioworks Brand Guidelines presentation, page 38 of 45'),
  ('materia-bioworks-brand-guidelines', 38, './page-39.png', 'Materia Bioworks Brand Guidelines presentation, page 39 of 45'),
  ('materia-bioworks-brand-guidelines', 39, './page-40.png', 'Materia Bioworks Brand Guidelines presentation, page 40 of 45'),
  ('materia-bioworks-brand-guidelines', 40, './page-41.png', 'Materia Bioworks Brand Guidelines presentation, page 41 of 45'),
  ('materia-bioworks-brand-guidelines', 41, './page-42.png', 'Materia Bioworks Brand Guidelines presentation, page 42 of 45'),
  ('materia-bioworks-brand-guidelines', 42, './page-43.png', 'Materia Bioworks Brand Guidelines presentation, page 43 of 45'),
  ('materia-bioworks-brand-guidelines', 43, './page-44.png', 'Materia Bioworks Brand Guidelines presentation, page 44 of 45'),
  ('materia-bioworks-brand-guidelines', 44, './page-45.png', 'Materia Bioworks Brand Guidelines presentation, page 45 of 45');

-- Noodles
INSERT INTO projects (slug, title, category, logo_type, guideline_type, industry, website, instagram, facebook, linkedin, other_links, extras, extras_custom, sort_order, summary, intent, context, challenge, direction, delivered, outcome, testimonial, pdf, cover, cover_alt)
VALUES ('noodles', 'Noodles', 'logo-design', 'Combination', NULL, 'Communication Technology', NULL, NULL, NULL, NULL, '[]', '[]', '[]', 7, 'A sophisticated brand identity designed for Noodles, a modern technology platform centered on warm, private, and meaningful digital communication. The visual system combines refined minimalism with a distinctive symbolic mark, creating a premium identity that conveys trust, intimacy, and contemporary elegance while standing apart from conventional technology and social platform branding.', 'Refined minimalism for a messaging platform built on warmth and privacy.', NULL, NULL, NULL, '[]', NULL, NULL, 'Noodles Branding kit.pdf', './cover.png', 'Noodles presentation cover')
ON DUPLICATE KEY UPDATE title = VALUES(title), category = VALUES(category), logo_type = VALUES(logo_type), guideline_type = VALUES(guideline_type), industry = VALUES(industry), website = VALUES(website), instagram = VALUES(instagram), facebook = VALUES(facebook), linkedin = VALUES(linkedin), other_links = VALUES(other_links), extras = VALUES(extras), extras_custom = VALUES(extras_custom), sort_order = VALUES(sort_order), summary = VALUES(summary), intent = VALUES(intent), context = VALUES(context), challenge = VALUES(challenge), direction = VALUES(direction), delivered = VALUES(delivered), outcome = VALUES(outcome), testimonial = VALUES(testimonial), pdf = VALUES(pdf), cover = VALUES(cover), cover_alt = VALUES(cover_alt);
DELETE FROM project_images WHERE project_slug = 'noodles';
INSERT INTO project_images (project_slug, sort_order, src, alt) VALUES
  ('noodles', 0, './page-01.png', 'Noodles presentation, page 1 of 2'),
  ('noodles', 1, './page-02.png', 'Noodles presentation, page 2 of 2');

-- Orris Glow Brand Guidelines
INSERT INTO projects (slug, title, category, logo_type, guideline_type, industry, website, instagram, facebook, linkedin, other_links, extras, extras_custom, sort_order, summary, intent, context, challenge, direction, delivered, outcome, testimonial, pdf, cover, cover_alt)
VALUES ('orris-glow-brand-guidelines', 'Orris Glow Brand Guidelines', 'brand-guidelines', 'Wordmark', 'Full Brand Guidelines', 'Piercing Studio', NULL, NULL, NULL, NULL, '[]', '[\"Social Media Kit\"]', '[]', 6, 'A refined brand identity designed for Orris Glow, a modern ear piercing studio focused on precision, safety, and effortless elegance. The visual system embraces soft neutral tones and minimalist aesthetics to create a calm, premium brand experience that resonates with style-conscious clients seeking professional, high-quality piercing services.', 'Calm neutrals and quiet minimalism for a precision piercing studio.', NULL, NULL, NULL, '[]', NULL, NULL, 'Orris glow Brand Guidelines.pdf', './cover.png', 'Orris Glow Brand Guidelines presentation cover')
ON DUPLICATE KEY UPDATE title = VALUES(title), category = VALUES(category), logo_type = VALUES(logo_type), guideline_type = VALUES(guideline_type), industry = VALUES(industry), website = VALUES(website), instagram = VALUES(instagram), facebook = VALUES(facebook), linkedin = VALUES(linkedin), other_links = VALUES(other_links), extras = VALUES(extras), extras_custom = VALUES(extras_custom), sort_order = VALUES(sort_order), summary = VALUES(summary), intent = VALUES(intent), context = VALUES(context), challenge = VALUES(challenge), direction = VALUES(direction), delivered = VALUES(delivered), outcome = VALUES(outcome), testimonial = VALUES(testimonial), pdf = VALUES(pdf), cover = VALUES(cover), cover_alt = VALUES(cover_alt);
DELETE FROM project_images WHERE project_slug = 'orris-glow-brand-guidelines';
INSERT INTO project_images (project_slug, sort_order, src, alt) VALUES
  ('orris-glow-brand-guidelines', 0, './page-01.png', 'Orris Glow Brand Guidelines presentation, page 1 of 32'),
  ('orris-glow-brand-guidelines', 1, './page-02.png', 'Orris Glow Brand Guidelines presentation, page 2 of 32'),
  ('orris-glow-brand-guidelines', 2, './page-03.png', 'Orris Glow Brand Guidelines presentation, page 3 of 32'),
  ('orris-glow-brand-guidelines', 3, './page-04.png', 'Orris Glow Brand Guidelines presentation, page 4 of 32'),
  ('orris-glow-brand-guidelines', 4, './page-05.png', 'Orris Glow Brand Guidelines presentation, page 5 of 32'),
  ('orris-glow-brand-guidelines', 5, './page-06.png', 'Orris Glow Brand Guidelines presentation, page 6 of 32'),
  ('orris-glow-brand-guidelines', 6, './page-07.png', 'Orris Glow Brand Guidelines presentation, page 7 of 32'),
  ('orris-glow-brand-guidelines', 7, './page-08.png', 'Orris Glow Brand Guidelines presentation, page 8 of 32'),
  ('orris-glow-brand-guidelines', 8, './page-09.png', 'Orris Glow Brand Guidelines presentation, page 9 of 32'),
  ('orris-glow-brand-guidelines', 9, './page-10.png', 'Orris Glow Brand Guidelines presentation, page 10 of 32'),
  ('orris-glow-brand-guidelines', 10, './page-11.png', 'Orris Glow Brand Guidelines presentation, page 11 of 32'),
  ('orris-glow-brand-guidelines', 11, './page-12.png', 'Orris Glow Brand Guidelines presentation, page 12 of 32'),
  ('orris-glow-brand-guidelines', 12, './page-13.png', 'Orris Glow Brand Guidelines presentation, page 13 of 32'),
  ('orris-glow-brand-guidelines', 13, './page-14.png', 'Orris Glow Brand Guidelines presentation, page 14 of 32'),
  ('orris-glow-brand-guidelines', 14, './page-15.png', 'Orris Glow Brand Guidelines presentation, page 15 of 32'),
  ('orris-glow-brand-guidelines', 15, './page-16.png', 'Orris Glow Brand Guidelines presentation, page 16 of 32'),
  ('orris-glow-brand-guidelines', 16, './page-17.png', 'Orris Glow Brand Guidelines presentation, page 17 of 32'),
  ('orris-glow-brand-guidelines', 17, './page-18.png', 'Orris Glow Brand Guidelines presentation, page 18 of 32'),
  ('orris-glow-brand-guidelines', 18, './page-19.png', 'Orris Glow Brand Guidelines presentation, page 19 of 32'),
  ('orris-glow-brand-guidelines', 19, './page-20.png', 'Orris Glow Brand Guidelines presentation, page 20 of 32'),
  ('orris-glow-brand-guidelines', 20, './page-21.png', 'Orris Glow Brand Guidelines presentation, page 21 of 32'),
  ('orris-glow-brand-guidelines', 21, './page-22.png', 'Orris Glow Brand Guidelines presentation, page 22 of 32'),
  ('orris-glow-brand-guidelines', 22, './page-23.png', 'Orris Glow Brand Guidelines presentation, page 23 of 32'),
  ('orris-glow-brand-guidelines', 23, './page-24.png', 'Orris Glow Brand Guidelines presentation, page 24 of 32'),
  ('orris-glow-brand-guidelines', 24, './page-25.png', 'Orris Glow Brand Guidelines presentation, page 25 of 32'),
  ('orris-glow-brand-guidelines', 25, './page-26.png', 'Orris Glow Brand Guidelines presentation, page 26 of 32'),
  ('orris-glow-brand-guidelines', 26, './page-27.png', 'Orris Glow Brand Guidelines presentation, page 27 of 32'),
  ('orris-glow-brand-guidelines', 27, './page-28.png', 'Orris Glow Brand Guidelines presentation, page 28 of 32'),
  ('orris-glow-brand-guidelines', 28, './page-29.png', 'Orris Glow Brand Guidelines presentation, page 29 of 32'),
  ('orris-glow-brand-guidelines', 29, './page-30.png', 'Orris Glow Brand Guidelines presentation, page 30 of 32'),
  ('orris-glow-brand-guidelines', 30, './page-31.png', 'Orris Glow Brand Guidelines presentation, page 31 of 32'),
  ('orris-glow-brand-guidelines', 31, './page-32.png', 'Orris Glow Brand Guidelines presentation, page 32 of 32');

-- Rad Soft Brand Guidelines
INSERT INTO projects (slug, title, category, logo_type, guideline_type, industry, website, instagram, facebook, linkedin, other_links, extras, extras_custom, sort_order, summary, intent, context, challenge, direction, delivered, outcome, testimonial, pdf, cover, cover_alt)
VALUES ('rad-soft-brand-guidelines', 'Rad Soft Brand Guidelines', 'brand-guidelines', 'Abstract', 'Full Brand Guidelines', 'Software & Technology', 'www.radsoftinc.com', NULL, NULL, 'www.linkedin.com/company/rad-soft/', '[]', '[\"Social Media Kit\",\"Stationery Design Kit\"]', '[]', 4, 'A modern brand identity developed for Rad Soft, a product-focused software studio dedicated to building innovative digital products and applications. The visual system combines minimalism with refined geometric design, creating a scalable identity that communicates precision, innovation, and a premium technology-first approach across digital platforms and software ecosystems.', 'Geometric precision for a product studio that ships software.', NULL, NULL, NULL, '[]', NULL, NULL, 'Rad Soft Brand Guidelines.pdf', './cover.png', 'Rad Soft Brand Guidelines presentation cover')
ON DUPLICATE KEY UPDATE title = VALUES(title), category = VALUES(category), logo_type = VALUES(logo_type), guideline_type = VALUES(guideline_type), industry = VALUES(industry), website = VALUES(website), instagram = VALUES(instagram), facebook = VALUES(facebook), linkedin = VALUES(linkedin), other_links = VALUES(other_links), extras = VALUES(extras), extras_custom = VALUES(extras_custom), sort_order = VALUES(sort_order), summary = VALUES(summary), intent = VALUES(intent), context = VALUES(context), challenge = VALUES(challenge), direction = VALUES(direction), delivered = VALUES(delivered), outcome = VALUES(outcome), testimonial = VALUES(testimonial), pdf = VALUES(pdf), cover = VALUES(cover), cover_alt = VALUES(cover_alt);
DELETE FROM project_images WHERE project_slug = 'rad-soft-brand-guidelines';
INSERT INTO project_images (project_slug, sort_order, src, alt) VALUES
  ('rad-soft-brand-guidelines', 0, './page-01.png', 'Rad Soft Brand Guidelines presentation, page 1 of 39'),
  ('rad-soft-brand-guidelines', 1, './page-02.png', 'Rad Soft Brand Guidelines presentation, page 2 of 39'),
  ('rad-soft-brand-guidelines', 2, './page-03.png', 'Rad Soft Brand Guidelines presentation, page 3 of 39'),
  ('rad-soft-brand-guidelines', 3, './page-04.png', 'Rad Soft Brand Guidelines presentation, page 4 of 39'),
  ('rad-soft-brand-guidelines', 4, './page-05.png', 'Rad Soft Brand Guidelines presentation, page 5 of 39'),
  ('rad-soft-brand-guidelines', 5, './page-06.png', 'Rad Soft Brand Guidelines presentation, page 6 of 39'),
  ('rad-soft-brand-guidelines', 6, './page-07.png', 'Rad Soft Brand Guidelines presentation, page 7 of 39'),
  ('rad-soft-brand-guidelines', 7, './page-08.png', 'Rad Soft Brand Guidelines presentation, page 8 of 39'),
  ('rad-soft-brand-guidelines', 8, './page-09.png', 'Rad Soft Brand Guidelines presentation, page 9 of 39'),
  ('rad-soft-brand-guidelines', 9, './page-10.png', 'Rad Soft Brand Guidelines presentation, page 10 of 39'),
  ('rad-soft-brand-guidelines', 10, './page-11.png', 'Rad Soft Brand Guidelines presentation, page 11 of 39'),
  ('rad-soft-brand-guidelines', 11, './page-12.png', 'Rad Soft Brand Guidelines presentation, page 12 of 39'),
  ('rad-soft-brand-guidelines', 12, './page-13.png', 'Rad Soft Brand Guidelines presentation, page 13 of 39'),
  ('rad-soft-brand-guidelines', 13, './page-14.png', 'Rad Soft Brand Guidelines presentation, page 14 of 39'),
  ('rad-soft-brand-guidelines', 14, './page-15.png', 'Rad Soft Brand Guidelines presentation, page 15 of 39'),
  ('rad-soft-brand-guidelines', 15, './page-16.png', 'Rad Soft Brand Guidelines presentation, page 16 of 39'),
  ('rad-soft-brand-guidelines', 16, './page-17.png', 'Rad Soft Brand Guidelines presentation, page 17 of 39'),
  ('rad-soft-brand-guidelines', 17, './page-18.png', 'Rad Soft Brand Guidelines presentation, page 18 of 39'),
  ('rad-soft-brand-guidelines', 18, './page-19.png', 'Rad Soft Brand Guidelines presentation, page 19 of 39'),
  ('rad-soft-brand-guidelines', 19, './page-20.png', 'Rad Soft Brand Guidelines presentation, page 20 of 39'),
  ('rad-soft-brand-guidelines', 20, './page-21.png', 'Rad Soft Brand Guidelines presentation, page 21 of 39'),
  ('rad-soft-brand-guidelines', 21, './page-22.png', 'Rad Soft Brand Guidelines presentation, page 22 of 39'),
  ('rad-soft-brand-guidelines', 22, './page-23.png', 'Rad Soft Brand Guidelines presentation, page 23 of 39'),
  ('rad-soft-brand-guidelines', 23, './page-24.png', 'Rad Soft Brand Guidelines presentation, page 24 of 39'),
  ('rad-soft-brand-guidelines', 24, './page-25.png', 'Rad Soft Brand Guidelines presentation, page 25 of 39'),
  ('rad-soft-brand-guidelines', 25, './page-26.png', 'Rad Soft Brand Guidelines presentation, page 26 of 39'),
  ('rad-soft-brand-guidelines', 26, './page-27.png', 'Rad Soft Brand Guidelines presentation, page 27 of 39'),
  ('rad-soft-brand-guidelines', 27, './page-28.png', 'Rad Soft Brand Guidelines presentation, page 28 of 39'),
  ('rad-soft-brand-guidelines', 28, './page-29.png', 'Rad Soft Brand Guidelines presentation, page 29 of 39'),
  ('rad-soft-brand-guidelines', 29, './page-30.png', 'Rad Soft Brand Guidelines presentation, page 30 of 39'),
  ('rad-soft-brand-guidelines', 30, './page-31.png', 'Rad Soft Brand Guidelines presentation, page 31 of 39'),
  ('rad-soft-brand-guidelines', 31, './page-32.png', 'Rad Soft Brand Guidelines presentation, page 32 of 39'),
  ('rad-soft-brand-guidelines', 32, './page-33.png', 'Rad Soft Brand Guidelines presentation, page 33 of 39'),
  ('rad-soft-brand-guidelines', 33, './page-34.png', 'Rad Soft Brand Guidelines presentation, page 34 of 39'),
  ('rad-soft-brand-guidelines', 34, './page-35.png', 'Rad Soft Brand Guidelines presentation, page 35 of 39'),
  ('rad-soft-brand-guidelines', 35, './page-36.png', 'Rad Soft Brand Guidelines presentation, page 36 of 39'),
  ('rad-soft-brand-guidelines', 36, './page-37.png', 'Rad Soft Brand Guidelines presentation, page 37 of 39'),
  ('rad-soft-brand-guidelines', 37, './page-38.png', 'Rad Soft Brand Guidelines presentation, page 38 of 39'),
  ('rad-soft-brand-guidelines', 38, './page-39.png', 'Rad Soft Brand Guidelines presentation, page 39 of 39');

-- Suh Family Dentistry
INSERT INTO projects (slug, title, category, logo_type, guideline_type, industry, website, instagram, facebook, linkedin, other_links, extras, extras_custom, sort_order, summary, intent, context, challenge, direction, delivered, outcome, testimonial, pdf, cover, cover_alt)
VALUES ('suh-family-dentistry', 'Suh Family Dentistry', 'logo-design', 'Combination', NULL, 'Dental Care', 'https://suhfamilydentistry.com/', NULL, NULL, NULL, '[]', '[]', '[]', 8, 'A warm and approachable brand identity designed for Suh Family Dentistry, a family-focused dental practice serving both adults and children. The visual system balances professional healthcare standards with welcoming, modern aesthetics, creating a trusted brand presence that reflects compassionate care, lasting relationships, and a comfortable experience for patients of every age.', 'Clinical trust with a welcome in it, for a family dental practice.', NULL, NULL, NULL, '[]', NULL, NULL, 'Suh Family Dentistry branding kit.pdf', './cover.png', 'Suh Family Dentistry presentation cover')
ON DUPLICATE KEY UPDATE title = VALUES(title), category = VALUES(category), logo_type = VALUES(logo_type), guideline_type = VALUES(guideline_type), industry = VALUES(industry), website = VALUES(website), instagram = VALUES(instagram), facebook = VALUES(facebook), linkedin = VALUES(linkedin), other_links = VALUES(other_links), extras = VALUES(extras), extras_custom = VALUES(extras_custom), sort_order = VALUES(sort_order), summary = VALUES(summary), intent = VALUES(intent), context = VALUES(context), challenge = VALUES(challenge), direction = VALUES(direction), delivered = VALUES(delivered), outcome = VALUES(outcome), testimonial = VALUES(testimonial), pdf = VALUES(pdf), cover = VALUES(cover), cover_alt = VALUES(cover_alt);
DELETE FROM project_images WHERE project_slug = 'suh-family-dentistry';
INSERT INTO project_images (project_slug, sort_order, src, alt) VALUES
  ('suh-family-dentistry', 0, './page-01.png', 'Suh Family Dentistry presentation, page 1 of 2'),
  ('suh-family-dentistry', 1, './page-02.png', 'Suh Family Dentistry presentation, page 2 of 2');

-- Wren and Rook Brand Guidelines
INSERT INTO projects (slug, title, category, logo_type, guideline_type, industry, website, instagram, facebook, linkedin, other_links, extras, extras_custom, sort_order, summary, intent, context, challenge, direction, delivered, outcome, testimonial, pdf, cover, cover_alt)
VALUES ('wren-and-rook-brand-guidelines', 'Wren and Rook Brand Guidelines', 'brand-guidelines', 'Pictorial', 'Full Brand Guidelines', 'Cafe', NULL, NULL, NULL, NULL, '[]', '[]', '[\"Business Card\"]', 5, 'A distinctive brand identity crafted for Wren & Rook, a board game café where exceptional coffee, quality food, and a curated library of games create a welcoming social experience. The visual system blends warmth, wit, and understated character, capturing a clever yet relaxed atmosphere that invites guests to stay, connect, and play without limits.', 'Warmth and wit for a board-game cafe built for staying put.', NULL, NULL, NULL, '[]', NULL, NULL, 'Wren and Rook Brand Guidelines.pdf', './cover.png', 'Wren and Rook Brand Guidelines presentation cover')
ON DUPLICATE KEY UPDATE title = VALUES(title), category = VALUES(category), logo_type = VALUES(logo_type), guideline_type = VALUES(guideline_type), industry = VALUES(industry), website = VALUES(website), instagram = VALUES(instagram), facebook = VALUES(facebook), linkedin = VALUES(linkedin), other_links = VALUES(other_links), extras = VALUES(extras), extras_custom = VALUES(extras_custom), sort_order = VALUES(sort_order), summary = VALUES(summary), intent = VALUES(intent), context = VALUES(context), challenge = VALUES(challenge), direction = VALUES(direction), delivered = VALUES(delivered), outcome = VALUES(outcome), testimonial = VALUES(testimonial), pdf = VALUES(pdf), cover = VALUES(cover), cover_alt = VALUES(cover_alt);
DELETE FROM project_images WHERE project_slug = 'wren-and-rook-brand-guidelines';
INSERT INTO project_images (project_slug, sort_order, src, alt) VALUES
  ('wren-and-rook-brand-guidelines', 0, './page-01.png', 'Wren and Rook Brand Guidelines presentation, page 1 of 38'),
  ('wren-and-rook-brand-guidelines', 1, './page-02.png', 'Wren and Rook Brand Guidelines presentation, page 2 of 38'),
  ('wren-and-rook-brand-guidelines', 2, './page-03.png', 'Wren and Rook Brand Guidelines presentation, page 3 of 38'),
  ('wren-and-rook-brand-guidelines', 3, './page-04.png', 'Wren and Rook Brand Guidelines presentation, page 4 of 38'),
  ('wren-and-rook-brand-guidelines', 4, './page-05.png', 'Wren and Rook Brand Guidelines presentation, page 5 of 38'),
  ('wren-and-rook-brand-guidelines', 5, './page-06.png', 'Wren and Rook Brand Guidelines presentation, page 6 of 38'),
  ('wren-and-rook-brand-guidelines', 6, './page-07.png', 'Wren and Rook Brand Guidelines presentation, page 7 of 38'),
  ('wren-and-rook-brand-guidelines', 7, './page-08.png', 'Wren and Rook Brand Guidelines presentation, page 8 of 38'),
  ('wren-and-rook-brand-guidelines', 8, './page-09.png', 'Wren and Rook Brand Guidelines presentation, page 9 of 38'),
  ('wren-and-rook-brand-guidelines', 9, './page-10.png', 'Wren and Rook Brand Guidelines presentation, page 10 of 38'),
  ('wren-and-rook-brand-guidelines', 10, './page-11.png', 'Wren and Rook Brand Guidelines presentation, page 11 of 38'),
  ('wren-and-rook-brand-guidelines', 11, './page-12.png', 'Wren and Rook Brand Guidelines presentation, page 12 of 38'),
  ('wren-and-rook-brand-guidelines', 12, './page-13.png', 'Wren and Rook Brand Guidelines presentation, page 13 of 38'),
  ('wren-and-rook-brand-guidelines', 13, './page-14.png', 'Wren and Rook Brand Guidelines presentation, page 14 of 38'),
  ('wren-and-rook-brand-guidelines', 14, './page-15.png', 'Wren and Rook Brand Guidelines presentation, page 15 of 38'),
  ('wren-and-rook-brand-guidelines', 15, './page-16.png', 'Wren and Rook Brand Guidelines presentation, page 16 of 38'),
  ('wren-and-rook-brand-guidelines', 16, './page-17.png', 'Wren and Rook Brand Guidelines presentation, page 17 of 38'),
  ('wren-and-rook-brand-guidelines', 17, './page-18.png', 'Wren and Rook Brand Guidelines presentation, page 18 of 38'),
  ('wren-and-rook-brand-guidelines', 18, './page-19.png', 'Wren and Rook Brand Guidelines presentation, page 19 of 38'),
  ('wren-and-rook-brand-guidelines', 19, './page-20.png', 'Wren and Rook Brand Guidelines presentation, page 20 of 38'),
  ('wren-and-rook-brand-guidelines', 20, './page-21.png', 'Wren and Rook Brand Guidelines presentation, page 21 of 38'),
  ('wren-and-rook-brand-guidelines', 21, './page-22.png', 'Wren and Rook Brand Guidelines presentation, page 22 of 38'),
  ('wren-and-rook-brand-guidelines', 22, './page-23.png', 'Wren and Rook Brand Guidelines presentation, page 23 of 38'),
  ('wren-and-rook-brand-guidelines', 23, './page-24.png', 'Wren and Rook Brand Guidelines presentation, page 24 of 38'),
  ('wren-and-rook-brand-guidelines', 24, './page-25.png', 'Wren and Rook Brand Guidelines presentation, page 25 of 38'),
  ('wren-and-rook-brand-guidelines', 25, './page-26.png', 'Wren and Rook Brand Guidelines presentation, page 26 of 38'),
  ('wren-and-rook-brand-guidelines', 26, './page-27.png', 'Wren and Rook Brand Guidelines presentation, page 27 of 38'),
  ('wren-and-rook-brand-guidelines', 27, './page-28.png', 'Wren and Rook Brand Guidelines presentation, page 28 of 38'),
  ('wren-and-rook-brand-guidelines', 28, './page-29.png', 'Wren and Rook Brand Guidelines presentation, page 29 of 38'),
  ('wren-and-rook-brand-guidelines', 29, './page-30.png', 'Wren and Rook Brand Guidelines presentation, page 30 of 38'),
  ('wren-and-rook-brand-guidelines', 30, './page-31.png', 'Wren and Rook Brand Guidelines presentation, page 31 of 38'),
  ('wren-and-rook-brand-guidelines', 31, './page-32.png', 'Wren and Rook Brand Guidelines presentation, page 32 of 38'),
  ('wren-and-rook-brand-guidelines', 32, './page-33.png', 'Wren and Rook Brand Guidelines presentation, page 33 of 38'),
  ('wren-and-rook-brand-guidelines', 33, './page-34.png', 'Wren and Rook Brand Guidelines presentation, page 34 of 38'),
  ('wren-and-rook-brand-guidelines', 34, './page-35.png', 'Wren and Rook Brand Guidelines presentation, page 35 of 38'),
  ('wren-and-rook-brand-guidelines', 35, './page-36.png', 'Wren and Rook Brand Guidelines presentation, page 36 of 38'),
  ('wren-and-rook-brand-guidelines', 36, './page-37.png', 'Wren and Rook Brand Guidelines presentation, page 37 of 38'),
  ('wren-and-rook-brand-guidelines', 37, './page-38.png', 'Wren and Rook Brand Guidelines presentation, page 38 of 38');

-- Zion Ventures Brand Guidelines
INSERT INTO projects (slug, title, category, logo_type, guideline_type, industry, website, instagram, facebook, linkedin, other_links, extras, extras_custom, sort_order, summary, intent, context, challenge, direction, delivered, outcome, testimonial, pdf, cover, cover_alt)
VALUES ('zion-ventures-brand-guidelines', 'Zion Ventures Brand Guidelines', 'brand-guidelines', 'Combination', 'Full Brand Guidelines', 'Capital & Investment', NULL, NULL, NULL, NULL, '[]', '[]', '[]', 1, 'A premium brand identity crafted for Zion Ventures, blending luxury minimalism with futuristic design principles to reflect innovation, strategic investment, and long-term growth. The visual identity establishes a sophisticated and trustworthy presence, positioning the brand as a forward-thinking venture partner for modern businesses and emerging technologies.', 'Luxury minimalism with a forward lean, for a venture investor.', NULL, NULL, NULL, '[]', NULL, NULL, 'Zion Ventures Brand Guidelines.pdf', './cover.png', 'Zion Ventures Brand Guidelines presentation cover')
ON DUPLICATE KEY UPDATE title = VALUES(title), category = VALUES(category), logo_type = VALUES(logo_type), guideline_type = VALUES(guideline_type), industry = VALUES(industry), website = VALUES(website), instagram = VALUES(instagram), facebook = VALUES(facebook), linkedin = VALUES(linkedin), other_links = VALUES(other_links), extras = VALUES(extras), extras_custom = VALUES(extras_custom), sort_order = VALUES(sort_order), summary = VALUES(summary), intent = VALUES(intent), context = VALUES(context), challenge = VALUES(challenge), direction = VALUES(direction), delivered = VALUES(delivered), outcome = VALUES(outcome), testimonial = VALUES(testimonial), pdf = VALUES(pdf), cover = VALUES(cover), cover_alt = VALUES(cover_alt);
DELETE FROM project_images WHERE project_slug = 'zion-ventures-brand-guidelines';
INSERT INTO project_images (project_slug, sort_order, src, alt) VALUES
  ('zion-ventures-brand-guidelines', 0, './page-01.png', 'Zion Ventures Brand Guidelines presentation, page 1 of 34'),
  ('zion-ventures-brand-guidelines', 1, './page-02.png', 'Zion Ventures Brand Guidelines presentation, page 2 of 34'),
  ('zion-ventures-brand-guidelines', 2, './page-03.png', 'Zion Ventures Brand Guidelines presentation, page 3 of 34'),
  ('zion-ventures-brand-guidelines', 3, './page-04.png', 'Zion Ventures Brand Guidelines presentation, page 4 of 34'),
  ('zion-ventures-brand-guidelines', 4, './page-05.png', 'Zion Ventures Brand Guidelines presentation, page 5 of 34'),
  ('zion-ventures-brand-guidelines', 5, './page-06.png', 'Zion Ventures Brand Guidelines presentation, page 6 of 34'),
  ('zion-ventures-brand-guidelines', 6, './page-07.png', 'Zion Ventures Brand Guidelines presentation, page 7 of 34'),
  ('zion-ventures-brand-guidelines', 7, './page-08.png', 'Zion Ventures Brand Guidelines presentation, page 8 of 34'),
  ('zion-ventures-brand-guidelines', 8, './page-09.png', 'Zion Ventures Brand Guidelines presentation, page 9 of 34'),
  ('zion-ventures-brand-guidelines', 9, './page-10.png', 'Zion Ventures Brand Guidelines presentation, page 10 of 34'),
  ('zion-ventures-brand-guidelines', 10, './page-11.png', 'Zion Ventures Brand Guidelines presentation, page 11 of 34'),
  ('zion-ventures-brand-guidelines', 11, './page-12.png', 'Zion Ventures Brand Guidelines presentation, page 12 of 34'),
  ('zion-ventures-brand-guidelines', 12, './page-13.png', 'Zion Ventures Brand Guidelines presentation, page 13 of 34'),
  ('zion-ventures-brand-guidelines', 13, './page-14.png', 'Zion Ventures Brand Guidelines presentation, page 14 of 34'),
  ('zion-ventures-brand-guidelines', 14, './page-15.png', 'Zion Ventures Brand Guidelines presentation, page 15 of 34'),
  ('zion-ventures-brand-guidelines', 15, './page-16.png', 'Zion Ventures Brand Guidelines presentation, page 16 of 34'),
  ('zion-ventures-brand-guidelines', 16, './page-17.png', 'Zion Ventures Brand Guidelines presentation, page 17 of 34'),
  ('zion-ventures-brand-guidelines', 17, './page-18.png', 'Zion Ventures Brand Guidelines presentation, page 18 of 34'),
  ('zion-ventures-brand-guidelines', 18, './page-19.png', 'Zion Ventures Brand Guidelines presentation, page 19 of 34'),
  ('zion-ventures-brand-guidelines', 19, './page-20.png', 'Zion Ventures Brand Guidelines presentation, page 20 of 34'),
  ('zion-ventures-brand-guidelines', 20, './page-21.png', 'Zion Ventures Brand Guidelines presentation, page 21 of 34'),
  ('zion-ventures-brand-guidelines', 21, './page-22.png', 'Zion Ventures Brand Guidelines presentation, page 22 of 34'),
  ('zion-ventures-brand-guidelines', 22, './page-23.png', 'Zion Ventures Brand Guidelines presentation, page 23 of 34'),
  ('zion-ventures-brand-guidelines', 23, './page-24.png', 'Zion Ventures Brand Guidelines presentation, page 24 of 34'),
  ('zion-ventures-brand-guidelines', 24, './page-25.png', 'Zion Ventures Brand Guidelines presentation, page 25 of 34'),
  ('zion-ventures-brand-guidelines', 25, './page-26.png', 'Zion Ventures Brand Guidelines presentation, page 26 of 34'),
  ('zion-ventures-brand-guidelines', 26, './page-27.png', 'Zion Ventures Brand Guidelines presentation, page 27 of 34'),
  ('zion-ventures-brand-guidelines', 27, './page-28.png', 'Zion Ventures Brand Guidelines presentation, page 28 of 34'),
  ('zion-ventures-brand-guidelines', 28, './page-29.png', 'Zion Ventures Brand Guidelines presentation, page 29 of 34'),
  ('zion-ventures-brand-guidelines', 29, './page-30.png', 'Zion Ventures Brand Guidelines presentation, page 30 of 34'),
  ('zion-ventures-brand-guidelines', 30, './page-31.png', 'Zion Ventures Brand Guidelines presentation, page 31 of 34'),
  ('zion-ventures-brand-guidelines', 31, './page-32.png', 'Zion Ventures Brand Guidelines presentation, page 32 of 34'),
  ('zion-ventures-brand-guidelines', 32, './page-33.png', 'Zion Ventures Brand Guidelines presentation, page 33 of 34'),
  ('zion-ventures-brand-guidelines', 33, './page-34.png', 'Zion Ventures Brand Guidelines presentation, page 34 of 34');

-- ----------------------------------------------------------------------
-- Brand & links
-- ----------------------------------------------------------------------

INSERT INTO site_settings (setting_key, setting_value)
VALUES ('name', 'XStudioz')
ON DUPLICATE KEY UPDATE setting_value = VALUES(setting_value);
INSERT INTO site_settings (setting_key, setting_value)
VALUES ('url', 'https://portfolio.xstudioz.com')
ON DUPLICATE KEY UPDATE setting_value = VALUES(setting_value);
INSERT INTO site_settings (setting_key, setting_value)
VALUES ('headline', 'Look like the brand you\'re becoming.')
ON DUPLICATE KEY UPDATE setting_value = VALUES(setting_value);
INSERT INTO site_settings (setting_key, setting_value)
VALUES ('lede', 'XStudioz builds logo and identity systems for founders who need to be taken seriously from the first impression. Designed as a system, documented so it holds, and delivered as files you own.')
ON DUPLICATE KEY UPDATE setting_value = VALUES(setting_value);
INSERT INTO site_settings (setting_key, setting_value)
VALUES ('tagline', 'Identity systems for brands that intend to be around.')
ON DUPLICATE KEY UPDATE setting_value = VALUES(setting_value);
INSERT INTO site_settings (setting_key, setting_value)
VALUES ('description', 'Logo and brand identity design for founders: logos, brand guidelines, stationery, social and animation, built as a system and delivered as files you own.')
ON DUPLICATE KEY UPDATE setting_value = VALUES(setting_value);
INSERT INTO site_settings (setting_key, setting_value)
VALUES ('fiverrUrl', 'https://www.fiverr.com/x_studioz')
ON DUPLICATE KEY UPDATE setting_value = VALUES(setting_value);
INSERT INTO site_settings (setting_key, setting_value)
VALUES ('linkedinUrl', NULL)
ON DUPLICATE KEY UPDATE setting_value = VALUES(setting_value);
INSERT INTO site_settings (setting_key, setting_value)
VALUES ('behanceUrl', NULL)
ON DUPLICATE KEY UPDATE setting_value = VALUES(setting_value);
INSERT INTO site_settings (setting_key, setting_value)
VALUES ('instagramUrl', NULL)
ON DUPLICATE KEY UPDATE setting_value = VALUES(setting_value);
INSERT INTO site_settings (setting_key, setting_value)
VALUES ('locale', 'en')
ON DUPLICATE KEY UPDATE setting_value = VALUES(setting_value);
