/**
 * Export the current content to db/seed.sql.
 *
 * Reads exactly what the site reads today — src/content/projects/<slug>/
 * index.json, src/data/categories.json and src/config/site.json — and emits
 * MySQL INSERTs matching db/schema.sql. Run it, import the result once in
 * phpMyAdmin, and the database holds the same portfolio the repo does.
 *
 * Idempotent by design: every statement is an INSERT … ON DUPLICATE KEY
 * UPDATE, so re-importing after an edit refreshes rows instead of failing on
 * a duplicate key. Deck pages are deleted and re-inserted per project, which
 * is the only way a page removed from a deck also disappears from the table.
 *
 *   node scripts/export-sql.mjs
 */
import { readFileSync, writeFileSync, readdirSync, existsSync } from 'node:fs';
import { join } from 'node:path';

const PROJECTS_DIR = 'src/content/projects';
const OUT = 'db/seed.sql';

const read = (path) => JSON.parse(readFileSync(path, 'utf8'));

/**
 * Quote a value for MySQL.
 *
 * Hand-rolled rather than pulled from a driver: this script's whole point is
 * to run with no database connection and no new dependency. It escapes every
 * sequence that can break out of a single-quoted MySQL string literal.
 * Everything it quotes comes from this repo, not from user input.
 */
const ESCAPES = {
  '\0': '\\0',
  '\b': '\\b',
  '\t': '\\t',
  '\n': '\\n',
  '\r': '\\r',
  '\u001a': '\\Z',
  '"': '\\"',
  "'": "\\'",
  '\\': '\\\\',
};

const q = (value) => {
  if (value === undefined || value === null || value === '') return 'NULL';
  return `'${String(value).replace(/[\0\b\t\n\r\u001a"'\\]/g, (c) => ESCAPES[c])}'`;
};

/** A JSON column. Empty and missing both become '[]' — never NULL. */
const jsonArray = (value) => q(JSON.stringify(Array.isArray(value) ? value.filter(Boolean) : []));

/** An optional JSON object column: absent stays NULL so the section hides. */
const jsonObject = (value) =>
  value && Object.keys(value).length > 0 ? q(JSON.stringify(value)) : 'NULL';

/** INSERT … ON DUPLICATE KEY UPDATE over the given columns. */
const upsert = (table, columns, values) => {
  const assignments = columns
    .filter((c) => c !== 'id' && c !== 'slug' && c !== 'setting_key')
    .map((c) => `${c} = VALUES(${c})`)
    .join(', ');
  return (
    `INSERT INTO ${table} (${columns.join(', ')})\n` +
    `VALUES (${values.join(', ')})\n` +
    `ON DUPLICATE KEY UPDATE ${assignments};`
  );
};

const lines = [
  '-- Generated by scripts/export-sql.mjs — do not edit by hand.',
  '-- Import in hPanel → phpMyAdmin with your database selected.',
  '-- Safe to re-import: every statement upserts.',
  '',
  'SET NAMES utf8mb4;',
  '',
];

// --- Services -------------------------------------------------------------
const { categories } = read('src/data/categories.json');
lines.push('-- ' + '-'.repeat(70), '-- Services', '-- ' + '-'.repeat(70), '');
for (const [i, c] of categories.entries()) {
  lines.push(
    upsert(
      'services',
      [
        'id',
        'title',
        'nav_label',
        'description',
        'outcome',
        'intro',
        'related_extras',
        'active',
        'sort_order',
      ],
      [
        q(c.id),
        q(c.title),
        q(c.navLabel),
        q(c.description),
        q(c.outcome),
        q(c.intro),
        jsonArray(c.relatedExtras),
        c.active === false ? 0 : 1,
        i,
      ],
    ),
    '',
  );
}

// --- Projects -------------------------------------------------------------
const slugs = readdirSync(PROJECTS_DIR, { withFileTypes: true })
  .filter((e) => e.isDirectory() && existsSync(join(PROJECTS_DIR, e.name, 'index.json')))
  .map((e) => e.name)
  .sort();

lines.push('-- ' + '-'.repeat(70), `-- Projects (${slugs.length})`, '-- ' + '-'.repeat(70), '');

let pageCount = 0;
for (const slug of slugs) {
  const d = read(join(PROJECTS_DIR, slug, 'index.json'));
  // The schema keeps one industry column; the CMS's free-text escape hatch
  // merges into it exactly as src/content.config.ts does, dropdown winning.
  const industry = (d.industry || d.industryNew || '').trim();

  lines.push(
    `-- ${d.title}`,
    upsert(
      'projects',
      [
        'slug',
        'title',
        'category',
        'logo_type',
        'guideline_type',
        'industry',
        'website',
        'instagram',
        'facebook',
        'linkedin',
        'other_links',
        'extras',
        'extras_custom',
        'sort_order',
        'summary',
        'intent',
        'context',
        'challenge',
        'direction',
        'delivered',
        'outcome',
        'testimonial',
        'pdf',
        'cover',
        'cover_alt',
      ],
      [
        q(slug),
        q(d.title),
        q(d.category),
        q(d.logoType),
        q(d.guidelineType),
        q(industry),
        q(d.website),
        q(d.instagram),
        q(d.facebook),
        q(d.linkedin),
        jsonArray(d.otherLinks),
        jsonArray(d.extras),
        jsonArray(d.extrasCustom),
        d.order ?? 99,
        q(d.summary),
        q(d.intent),
        q(d.context),
        q(d.challenge),
        q(d.direction),
        jsonArray(d.delivered),
        q(d.outcome),
        jsonObject(d.testimonial),
        q(d.pdf),
        q(d.cover),
        q(d.coverAlt),
      ],
    ),
  );

  // Replace rather than upsert: a page dropped from a shorter deck has to
  // disappear, and an upsert would leave it behind at its old index.
  const images = d.images ?? [];
  lines.push(`DELETE FROM project_images WHERE project_slug = ${q(slug)};`);
  if (images.length > 0) {
    const rows = images.map((img, i) => `  (${q(slug)}, ${i}, ${q(img.src)}, ${q(img.alt)})`);
    lines.push(
      'INSERT INTO project_images (project_slug, sort_order, src, alt) VALUES',
      `${rows.join(',\n')};`,
    );
  }
  lines.push('');
  pageCount += images.length;
}

// --- Site settings --------------------------------------------------------
const site = read('src/config/site.json');
lines.push('-- ' + '-'.repeat(70), '-- Brand & links', '-- ' + '-'.repeat(70), '');
for (const [key, value] of Object.entries(site)) {
  lines.push(
    upsert(
      'site_settings',
      ['setting_key', 'setting_value'],
      [q(key), q(typeof value === 'string' ? value : JSON.stringify(value))],
    ),
  );
}
lines.push('');

writeFileSync(OUT, lines.join('\n'), 'utf8');
console.log(
  `[export-sql] ${OUT}: ${categories.length} services, ${slugs.length} projects, ` +
    `${pageCount} deck pages, ${Object.keys(site).length} settings.`,
);
