/**
 * Serve an uploaded image.
 *
 * On Hostinger these files sit in `public_html/uploads/`, and Apache serves
 * an existing file directly without ever waking the Node process — so in
 * production this route is usually dead code. It exists because "usually" is
 * not "always": the rewrite rules are generated by the platform and can
 * change, and a portfolio whose images 404 after a redeploy is a worse outcome
 * than a route that rarely runs.
 *
 * It also makes local development work, where there is no Apache at all.
 */
import type { APIRoute } from 'astro';
import { readUpload } from '@/lib/uploads';

const TYPES: Record<string, string> = {
  webp: 'image/webp',
  png: 'image/png',
  jpg: 'image/jpeg',
  jpeg: 'image/jpeg',
  avif: 'image/avif',
  pdf: 'application/pdf',
};

export const GET: APIRoute = async ({ params }) => {
  const { slug, file } = params;
  if (!slug || !file) return new Response('Not found', { status: 404 });

  const body = await readUpload(slug, file);
  if (!body) return new Response('Not found', { status: 404 });

  const ext = file.split('.').pop()?.toLowerCase() ?? '';

  return new Response(new Uint8Array(body), {
    headers: {
      'Content-Type': TYPES[ext] ?? 'application/octet-stream',
      // Uploaded files are immutable: a re-upload writes a new deck under new
      // names rather than replacing bytes at the same URL, so a year is safe
      // and keeps repeat visits off the disk entirely.
      'Cache-Control': 'public, max-age=31536000, immutable',
      'Content-Length': String(body.length),
    },
  });
};
