import { defineCollection, z } from 'astro:content';
import { glob } from 'astro/loaders';
import { CATEGORY_IDS } from './data/categories';
import { LOGO_TYPES } from './data/logo-filters';

/**
 * One folder per project under src/content/projects/<slug>/:
 *   index.json  — metadata (this schema)
 *   *.png|jpg…  — images referenced relatively from index.json
 *
 * Real portfolios arrive as ONE asset per brand — either a tall
 * presentation image (`sheet.png`) or a `portfolio.pdf`. Drop it in the
 * folder and run `npm run ingest` (see scripts/ingest.mjs): page images,
 * the 4:3 grid cover and the download link are generated automatically.
 *
 * Adding a project = add a folder. Removing one = delete the folder.
 */
/** The CMS stores "empty" as '' or [] — normalize those to undefined. */
const emptyToUndef = (value: unknown) =>
  value === '' || (Array.isArray(value) && value.length === 0) ? undefined : value;

/** The CMS may store entry-relative image paths without the './' prefix. */
const relativize = (value: unknown) => {
  if (value === '' || value == null) return undefined;
  return typeof value === 'string' && !value.startsWith('.') && !value.startsWith('/')
    ? `./${value}`
    : value;
};

const projects = defineCollection({
  loader: glob({
    pattern: '*/index.json',
    base: './src/content/projects',
    generateId: ({ entry }) => entry.replace('/index.json', ''),
  }),
  schema: ({ image }) =>
    z.object({
      title: z.string(),
      category: z.enum(CATEGORY_IDS),
      /** Logo Design projects only: powers the Type dropdown filter. */
      logoType: z.enum(LOGO_TYPES).optional(),
      /** Logo Design projects only: powers the Industry dropdown filter. */
      industry: z.string().optional(),
      /** Kept optional for older entries; no longer shown anywhere. */
      year: z.number().int().optional(),
      /** Lower numbers appear first within the grid. */
      order: z.number().default(99),
      /** One-sentence description shown on the project page + meta description. */
      summary: z.string(),
      /**
       * CMS PDF upload (any filename). The build renders its pages and
       * generates cover + images automatically — leave those empty.
       */
      pdf: z.preprocess(emptyToUndef, z.string().optional()),
      /** 4:3 grid thumbnail. Generated by ingest for PDF projects. */
      cover: z.preprocess(relativize, image().optional()),
      coverAlt: z.preprocess(emptyToUndef, z.string().optional()),
      /** The portfolio content, in order: PDF pages, one tall sheet, or a set. */
      images: z.preprocess(
        emptyToUndef,
        z
          .array(
            z.object({
              src: z.preprocess(relativize, image()),
              alt: z.string(),
            }),
          )
          .min(1)
          .optional(),
      ),
    }),
});

export const collections = { projects };
